language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - "3.10"
install:
    - pip install tox
    - pip install tox-travis
    - pip install pep8
script:
    - tox
    - pep8 fixture_magic --max-line-length=120