name: linting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        python -m pip install pep8
    - name: Run pep8
      run: |
        pep8 fixture_magic --max-line-length=120
